linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: github.com/javanhut/easyhttp
  goconst:
    min-len: 2
    min-occurrences: 3
  funlen:
    lines: 80
    statements: 40

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

  disable:
    - maligned
    - prealloc

run:
  timeout: 5m
  modules-download-mode: readonly

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - goconst
        - funlen
        - lll
    - path: example/
      linters:
        - gomnd
        - goconst

  exclude:
    - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"
    - "should have a package comment, unless it's in another file for this package"
